#!/usr/bin/env node

'use strict';

const os = require('os');
const path = require('path');
const workerpool = require('workerpool');
const yargs = require('yargs');

main().catch(console.error);

async function main() {
  yargs
    .help('help', 'Show help.')
    .option('nosend', {
      describe: 'Do not send metrics.',
    })
    .option('pipelineJs', {
      describe: 'Path to the pipeline.',
      alias: 'p',
      default: './pipelines/reference.js',
    })
    .option('user', {
      describe: 'The username associated with the graph in Prometheus.',
      alias: 'u',
      default: os.userInfo().username
    })
    .option('nodeCountRatio', {
      describe: 'Ratio of total nodes to witness nodes.',
      alias: 'r',
      default: 2,
    })
    .options('failures', {
      describe: 'Number of byzantine failures to protect against.',
      alias: 'f',
      default: 1,
    });

  const {nosend, pipelineJs, user, nodeCountRatio, failures} = yargs.argv;
  const run = Date.now();

  const simulationPool = workerpool.pool(
    path.join(__dirname, 'simulation-worker.js'));

  setInterval(() => {
    console.log('WORKERPOOL STATUS', simulationPool.stats());
  }, 3000);

  const promises = [];
  for(let f = 1; f <= failures; f++) {
    const simulationOptions = {
      nosend,
      pipelineJs,
      user,
      run,
      witnessCount: (3 * f) + 1,
      nonwitnessCount: Math.floor(((3 * f) + 1) * nodeCountRatio)
    };
    promises.push(simulationPool.exec('runSimulation', [simulationOptions]));
  }

  await Promise.all(promises);

  simulationPool.terminate();
}
